### ISSUE TITLE
Exception in device view

### ISSUE THREAD

**Issue by korfuri** [gurucomputing/headscale-ui#47]
Running headscale-ui 2022.08.13-beta, when navigating to the device view, I'm greeted with a broken page and this error in the console:

```
devices.html.svelte-b457f55c.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at ul (devices.html.svelte-b457f55c.js:1:20977)
    at Ee (index-e1cee4d8.js:4:5046)
    at new dl (devices.html.svelte-b457f55c.js:1:22367)
    at Al (devices.html.svelte-b457f55c.js:1:39173)
    at Ee (index-e1cee4d8.js:4:5046)
    at new Il (devices.html.svelte-b457f55c.js:1:41561)
    at Ct (devices.html.svelte-b457f55c.js:1:49316)
    at At (devices.html.svelte-b457f55c.js:1:49600)
    at St (devices.html.svelte-b457f55c.js:1:47088)
    at Object.p (devices.html.svelte-b457f55c.js:1:46456)
```

Other views (including user view) work fine. There are devices in my tailnet, so this is probably not a case of the list of devices being empty.

Thanks!

**Comment by routerino** [comment]
an empty headscale instance shouldn't cause a problem either. I can't recreate the problem. If you could answer the following questions I'd appreciate it

* Browser you're using (I only test chrome and firefox/firefox mobile)
* Version of headscale (please test with 0.16.2)
* Anything that might be unusual about your machines, special characters in names, that sort of thing

**Comment by korfuri** [comment]
Ah, thanks for the pointer! I was running headscale 0.15, that was the issue. I upgraded and it fixed it.
